version: 2.1
orbs:
  node: circleci/node@5.0.2

parameters:
  logLevel:
    type: string
    description: "Log verbosity"
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""

jobs:
  test:
    executor: node/default
    steps:
      - run:
          command: echo "Log Level - << pipeline.parameters.logLevel >>"
          name: Run tests

workflows:
  test_workfow:
    when: << pipeline.parameters.logLevel >>
    jobs:
      - test
