on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - 'feature/**'
      - 'chore/**'
      - 'bug/**'
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger_circleci
        id: step1
        uses: vinnymac/trigger-circleci-pipeline-action@v1.0.4
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
